use_frameworks!

platform :ios, '10.0'

target 'LuckMiniGameEngine_Example' do
  pod 'LuckMiniGameEngine', :path => '../'

  target 'LuckMiniGameEngine_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
